project:
  type: website
  output-dir: out

# execute:
#   freeze: auto # re-render only changed chapters

website:
  title: "MScBioStat Pre-Stats Exercises"
  # navbar:
  #   left:
  #   - index.qmd

  sidebar:
  - id: exercises
    title: "MScBioStat Pre-Stats Exercises"
    style: "floating"
    collapse-level: 2
    align: left
    contents:
      - index.Rmd
      - exercises/block1.rmd
      - exercises/block2.rmd
      - exercises/block3.rmd
      - exercises/block4.rmd
      - exercises/block5.rmd
      - exercises/block6.rmd
      - exercises/block7.rmd
      - exercises/block8.rmd
html:
  css: out/webex.css
  include-after-body: out/webex.js
format:
  html:
    theme: sandstone
    toc: true
    css:
    - include/webex.css
    include-after-body:
    - include/webex.js
